import io
from datetime import datetime

# Optional imports with robust fallbacks
try:
    import docx
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

class FileExportGenerator:
    def __init__(self):
        pass

    def generate_docx(self, title: str, content: str) -> bytes:
        """
        Generates a Word Document (DOCX) representation of the content.
        Includes standardized header metadata.
        """
        out_io = io.BytesIO()
        
        if DOCX_AVAILABLE:
            try:
                doc = docx.Document()
                
                # Standard Header block
                doc.add_heading(title, level=1)
                doc.add_paragraph(f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
                doc.add_paragraph("Generated by MindVault AI")
                doc.add_paragraph("Version Number: 1.0.0")
                doc.add_paragraph("-" * 50)
                
                # Split content into paragraphs and headers
                lines = content.split("\n")
                for line in lines:
                    line = line.strip()
                    if not line:
                        continue
                    if line.startswith("# "):
                        doc.add_heading(line[2:], level=1)
                    elif line.startswith("## "):
                        doc.add_heading(line[3:], level=2)
                    elif line.startswith("### "):
                        doc.add_heading(line[4:], level=3)
                    elif line.startswith("- ") or line.startswith("* "):
                        doc.add_paragraph(line[2:], style='List Bullet')
                    else:
                        doc.add_paragraph(line)
                        
                doc.save(out_io)
                out_io.seek(0)
                return out_io.getvalue()
            except Exception as e:
                print(f"python-docx generation failed: {e}. Falling back to formatted raw txt.")
                
        # Fallback raw text export
        text_content = (
            f"DOCUMENT: {title}\n"
            f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
            f"Generated by MindVault AI\n"
            f"Version Number: 1.0.0\n"
            f"{'='*50}\n\n{content}"
        )
        return text_content.encode("utf-8")

    def generate_pdf(self, title: str, content: str) -> bytes:
        """
        Generates a PDF Document representation of the content.
        Includes standardized header metadata.
        """
        out_io = io.BytesIO()
        
        if PDF_AVAILABLE:
            try:
                doc = SimpleDocTemplate(out_io, pagesize=letter,
                                        rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54)
                styles = getSampleStyleSheet()
                
                # Modify sample Normal style for clean layout
                normal_style = styles["Normal"]
                normal_style.fontSize = 10
                normal_style.leading = 14
                normal_style.textColor = colors.HexColor("#2C2640")
                
                title_style = ParagraphStyle(
                    'ReportTitle',
                    parent=styles['Heading1'],
                    fontSize=22,
                    leading=26,
                    textColor=colors.HexColor("#4B3F9E"),
                    spaceAfter=10
                )
                
                meta_style = ParagraphStyle(
                    'DocMeta',
                    parent=normal_style,
                    fontSize=8,
                    textColor=colors.HexColor("#7A7590"),
                    spaceAfter=15
                )
                
                h2_style = ParagraphStyle(
                    'ReportH2',
                    parent=styles['Heading2'],
                    fontSize=14,
                    leading=18,
                    textColor=colors.HexColor("#F0A742"),
                    spaceBefore=14,
                    spaceAfter=6
                )

                h3_style = ParagraphStyle(
                    'ReportH3',
                    parent=styles['Heading3'],
                    fontSize=11,
                    leading=15,
                    textColor=colors.HexColor("#1C1638"),
                    spaceBefore=10,
                    spaceAfter=4
                )

                story = []
                story.append(Paragraph(title, title_style))
                story.append(Paragraph(f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC | Generated by MindVault AI | Version: 1.0.0", meta_style))
                story.append(Spacer(1, 10))

                lines = content.split("\n")
                for line in lines:
                    line = line.strip()
                    if not line:
                        continue
                    if line.startswith("# "):
                        story.append(Paragraph(line[2:], title_style))
                    elif line.startswith("## "):
                        story.append(Paragraph(line[3:], h2_style))
                    elif line.startswith("### "):
                        story.append(Paragraph(line[4:], h3_style))
                    elif line.startswith("- ") or line.startswith("* "):
                        bullet_style = ParagraphStyle(
                            'BulletItem',
                            parent=normal_style,
                            leftIndent=20,
                            firstLineIndent=-10,
                            spaceAfter=4
                        )
                        story.append(Paragraph(f"&bull; {line[2:]}", bullet_style))
                    else:
                        story.append(Paragraph(line, normal_style))
                        story.append(Spacer(1, 4))
                
                doc.build(story)
                out_io.seek(0)
                return out_io.getvalue()
            except Exception as e:
                print(f"reportlab PDF generation failed: {e}. Falling back to formatted raw txt.")
                
        # Fallback plain text format
        text_content = (
            f"DOCUMENT: {title}\n"
            f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
            f"Generated by MindVault AI\n"
            f"Version Number: 1.0.0\n"
            f"{'='*50}\n\n{content}"
        )
        return text_content.encode("utf-8")

    def generate_markdown(self, title: str, content: str) -> bytes:
        """
        Generates a Markdown file (.md) representation of the content.
        """
        text_content = (
            f"# {title}\n\n"
            f"**Timestamp:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC  \n"
            f"**Generated by:** MindVault AI  \n"
            f"**Version Number:** 1.0.0  \n\n"
            f"---\n\n"
            f"{content}"
        )
        return text_content.encode("utf-8")

    def generate_quotation(self, client_name: str, items: list[dict], terms: str) -> bytes:
        """
        Produces a structured DOCX with standardized header metadata.
        """
        out_io = io.BytesIO()
        
        if DOCX_AVAILABLE:
            try:
                doc = docx.Document()
                doc.add_heading("Quotation", level=1)
                
                # Standard metadata
                doc.add_paragraph(f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
                doc.add_paragraph("Generated by MindVault AI")
                doc.add_paragraph("Version Number: 1.0.0")
                doc.add_paragraph("-" * 50)
                
                doc.add_paragraph(f"Client Name: {client_name}")
                doc.add_paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
                
                table = doc.add_table(rows=1, cols=4)
                table.style = 'Table Grid'
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Description'
                hdr_cells[1].text = 'Qty'
                hdr_cells[2].text = 'Rate'
                hdr_cells[3].text = 'Line Total'
                
                subtotal = 0.0
                for item in items:
                    desc = item.get("description", "")
                    qty = int(item.get("qty", 0))
                    rate = float(item.get("rate", 0.0))
                    line_total = qty * rate
                    subtotal += line_total
                    
                    row_cells = table.add_row().cells
                    row_cells[0].text = desc
                    row_cells[1].text = str(qty)
                    row_cells[2].text = f"${rate:.2f}"
                    row_cells[3].text = f"${line_total:.2f}"
                
                tax = subtotal * 0.18
                grand_total = subtotal + tax
                
                doc.add_paragraph(f"\nSubtotal: ${subtotal:.2f}")
                doc.add_paragraph(f"GST (18%): ${tax:.2f}")
                doc.add_paragraph(f"Grand Total: ${grand_total:.2f}")
                doc.add_paragraph(f"\nTerms & Conditions:\n{terms}")
                
                doc.save(out_io)
                out_io.seek(0)
                return out_io.getvalue()
            except Exception as e:
                print(f"python-docx quotation generation failed: {e}. Falling back to text.")
                
        # Fallback raw text export
        subtotal = sum(int(item.get("qty", 0)) * float(item.get("rate", 0.0)) for item in items)
        tax = subtotal * 0.18
        grand_total = subtotal + tax
        
        text_content = (
            f"QUOTATION\n"
            f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
            f"Generated by MindVault AI\n"
            f"Version Number: 1.0.0\n"
            f"{'='*50}\n"
            f"Client Name: {client_name}\n"
            f"Date: {datetime.now().strftime('%Y-%m-%d')}\n\n"
            f"{'Description':<30}{'Qty':<6}{'Rate':<12}{'Total':<12}\n"
            f"{'-'*60}\n"
        )
        for item in items:
            desc = item.get("description", "")
            qty = int(item.get("qty", 0))
            rate = float(item.get("rate", 0.0))
            total = qty * rate
            text_content += f"{desc:<30}{qty:<6}${rate:<11.2f}${total:<11.2f}\n"
            
        text_content += (
            f"{'-'*60}\n"
            f"Subtotal: ${subtotal:.2f}\n"
            f"GST (18%): ${tax:.2f}\n"
            f"Grand Total: ${grand_total:.2f}\n\n"
            f"Terms & Conditions:\n{terms}"
        )
        return text_content.encode("utf-8")

    def generate_invoice(self, invoice_no: str, client_name: str, items: list[dict], due_date: str) -> bytes:
        """
        Produces a structured DOCX with standardized header metadata.
        """
        out_io = io.BytesIO()
        
        if DOCX_AVAILABLE:
            try:
                doc = docx.Document()
                doc.add_heading("Invoice", level=1)
                
                # Standard metadata
                doc.add_paragraph(f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
                doc.add_paragraph("Generated by MindVault AI")
                doc.add_paragraph("Version Number: 1.0.0")
                doc.add_paragraph("-" * 50)
                
                doc.add_paragraph(f"Invoice Number: {invoice_no}")
                doc.add_paragraph(f"Client Name: {client_name}")
                doc.add_paragraph(f"Issue Date: {datetime.now().strftime('%Y-%m-%d')}")
                doc.add_paragraph(f"Due Date: {due_date}")
                doc.add_paragraph(f"Payment Status: Unpaid")
                
                table = doc.add_table(rows=1, cols=4)
                table.style = 'Table Grid'
                hdr_cells = table.rows[0].cells
                hdr_cells[0].text = 'Description'
                hdr_cells[1].text = 'Qty'
                hdr_cells[2].text = 'Rate'
                hdr_cells[3].text = 'Line Total'
                
                subtotal = 0.0
                for item in items:
                    desc = item.get("description", "")
                    qty = int(item.get("qty", 0))
                    rate = float(item.get("rate", 0.0))
                    line_total = qty * rate
                    subtotal += line_total
                    
                    row_cells = table.add_row().cells
                    row_cells[0].text = desc
                    row_cells[1].text = str(qty)
                    row_cells[2].text = f"${rate:.2f}"
                    row_cells[3].text = f"${line_total:.2f}"
                
                tax = subtotal * 0.18
                grand_total = subtotal + tax
                
                doc.add_paragraph(f"\nSubtotal: ${subtotal:.2f}")
                doc.add_paragraph(f"GST (18%): ${tax:.2f}")
                doc.add_paragraph(f"Grand Total: ${grand_total:.2f}")
                
                doc.save(out_io)
                out_io.seek(0)
                return out_io.getvalue()
            except Exception as e:
                print(f"python-docx invoice generation failed: {e}. Falling back to text.")
                
        # Fallback raw text export
        subtotal = sum(int(item.get("qty", 0)) * float(item.get("rate", 0.0)) for item in items)
        tax = subtotal * 0.18
        grand_total = subtotal + tax
        
        text_content = (
            f"INVOICE\n"
            f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
            f"Generated by MindVault AI\n"
            f"Version Number: 1.0.0\n"
            f"{'='*50}\n"
            f"Invoice Number: {invoice_no}\n"
            f"Client Name: {client_name}\n"
            f"Issue Date: {datetime.now().strftime('%Y-%m-%d')}\n"
            f"Due Date: {due_date}\n"
            f"Payment Status: Unpaid\n\n"
            f"{'Description':<30}{'Qty':<6}{'Rate':<12}{'Total':<12}\n"
            f"{'-'*60}\n"
        )
        for item in items:
            desc = item.get("description", "")
            qty = int(item.get("qty", 0))
            rate = float(item.get("rate", 0.0))
            total = qty * rate
            text_content += f"{desc:<30}{qty:<6}${rate:<11.2f}${total:<11.2f}\n"
            
        text_content += (
            f"{'-'*60}\n"
            f"Subtotal: ${subtotal:.2f}\n"
            f"GST (18%): ${tax:.2f}\n"
            f"Grand Total: ${grand_total:.2f}\n"
        )
        return text_content.encode("utf-8")
